/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module pmu_fsm(clk, reset_n, req_idle, req_sleep, req_off, wake_up, pwr_stable, clk_stable, retention_ready, clk_gate_en, pwr_gate_en, retention_en, retention_save, retention_restore, dvfs_ctrl, reset_ctrl, pwr_state, seq_busy, error);
  wire _000_;
  wire [1:0] _001_;
  wire _002_;
  wire [1:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire [7:0] _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  input clk;
  output clk_gate_en;
  input clk_stable;
  wire [2:0] curr_state;
  output [1:0] dvfs_ctrl;
  output error;
  wire [2:0] next_state;
  output pwr_gate_en;
  input pwr_stable;
  output [1:0] pwr_state;
  input req_idle;
  wire req_idle_sync;
  input req_off;
  wire req_off_sync;
  input req_sleep;
  wire req_sleep_sync;
  output reset_ctrl;
  input reset_n;
  output retention_en;
  input retention_ready;
  output retention_restore;
  output retention_save;
  output seq_busy;
  wire [7:0] seq_timer;
  wire [3:0] sync_stage1;
  input wake_up;
  wire wake_up_sync;
  sky130_fd_sc_hd__clkinv_1 _064_ (
    .A(curr_state[2]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__clkinv_1 _065_ (
    .A(seq_timer[4]),
    .Y(_018_)
  );
  sky130_fd_sc_hd__clkinv_1 _066_ (
    .A(seq_timer[3]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__clkinv_1 _067_ (
    .A(seq_timer[2]),
    .Y(_020_)
  );
  sky130_fd_sc_hd__clkinv_1 _068_ (
    .A(req_off_sync),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _069_ (
    .A(curr_state[0]),
    .B(curr_state[1]),
    .Y(_022_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _070_ (
    .A(curr_state[1]),
    .SLEEP(curr_state[0]),
    .X(_023_)
  );
  sky130_fd_sc_hd__or3b_1 _071_ (
    .A(curr_state[0]),
    .B(curr_state[2]),
    .C_N(curr_state[1]),
    .X(_001_[1])
  );
  sky130_fd_sc_hd__o21ai_0 _072_ (
    .A1(curr_state[2]),
    .A2(_022_),
    .B1(_001_[1]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__a21bo_1 _073_ (
    .A1(curr_state[0]),
    .A2(curr_state[1]),
    .B1_N(curr_state[2]),
    .X(_024_)
  );
  sky130_fd_sc_hd__clkinv_1 _074_ (
    .A(_024_),
    .Y(seq_busy)
  );
  sky130_fd_sc_hd__nor2_1 _075_ (
    .A(curr_state[0]),
    .B(curr_state[1]),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nor2_1 _076_ (
    .A(curr_state[2]),
    .B(_025_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nor4_1 _077_ (
    .A(seq_timer[7]),
    .B(seq_timer[6]),
    .C(seq_timer[5]),
    .D(seq_timer[4]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand3_1 _078_ (
    .A(_019_),
    .B(_020_),
    .C(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand2_1 _079_ (
    .A(seq_timer[1]),
    .B(seq_timer[0]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand4_1 _080_ (
    .A(_019_),
    .B(_020_),
    .C(_026_),
    .D(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nor2_1 _081_ (
    .A(seq_timer[1]),
    .B(seq_timer[0]),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand2_1 _082_ (
    .A(curr_state[2]),
    .B(_023_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__clkinv_1 _083_ (
    .A(_031_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nor3_1 _084_ (
    .A(_029_),
    .B(_030_),
    .C(_031_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__and3b_1 _085_ (
    .A_N(curr_state[1]),
    .B(curr_state[2]),
    .C(curr_state[0]),
    .X(_033_)
  );
  sky130_fd_sc_hd__nand3b_1 _086_ (
    .A_N(curr_state[1]),
    .B(curr_state[2]),
    .C(curr_state[0]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _087_ (
    .A(curr_state[2]),
    .SLEEP(wake_up_sync),
    .X(_035_)
  );
  sky130_fd_sc_hd__a21oi_1 _088_ (
    .A1(curr_state[0]),
    .A2(curr_state[1]),
    .B1(req_off_sync),
    .Y(_036_)
  );
  sky130_fd_sc_hd__o21bai_1 _089_ (
    .A1(curr_state[0]),
    .A2(req_idle_sync),
    .B1_N(req_sleep_sync),
    .Y(_037_)
  );
  sky130_fd_sc_hd__or3_1 _090_ (
    .A(curr_state[1]),
    .B(curr_state[2]),
    .C(wake_up_sync),
    .X(_038_)
  );
  sky130_fd_sc_hd__o221ai_1 _091_ (
    .A1(_035_),
    .A2(_036_),
    .B1(_037_),
    .B2(_038_),
    .C1(_034_),
    .Y(next_state[0])
  );
  sky130_fd_sc_hd__nor3_1 _092_ (
    .A(curr_state[0]),
    .B(curr_state[1]),
    .C(_017_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand4_1 _093_ (
    .A(seq_timer[3]),
    .B(seq_timer[2]),
    .C(seq_timer[1]),
    .D(seq_timer[0]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand2_1 _094_ (
    .A(retention_ready),
    .B(_029_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand3b_1 _095_ (
    .A_N(retention_ready),
    .B(_026_),
    .C(_040_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__a41oi_1 _096_ (
    .A1(pwr_stable),
    .A2(clk_stable),
    .A3(_029_),
    .A4(_042_),
    .B1(_031_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__o21ai_0 _097_ (
    .A1(seq_timer[1]),
    .A2(seq_timer[0]),
    .B1(seq_timer[2]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__a31oi_1 _098_ (
    .A1(_019_),
    .A2(_026_),
    .A3(_044_),
    .B1(_034_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__o311a_1 _099_ (
    .A1(curr_state[0]),
    .A2(wake_up_sync),
    .A3(_021_),
    .B1(curr_state[1]),
    .C1(_017_),
    .X(_046_)
  );
  sky130_fd_sc_hd__nor3_1 _100_ (
    .A(_043_),
    .B(_045_),
    .C(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__o41ai_1 _101_ (
    .A1(curr_state[0]),
    .A2(curr_state[1]),
    .A3(_017_),
    .A4(_041_),
    .B1(_047_),
    .Y(next_state[1])
  );
  sky130_fd_sc_hd__nand2_1 _102_ (
    .A(_029_),
    .B(_042_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__a21o_1 _103_ (
    .A1(req_off_sync),
    .A2(_023_),
    .B1(_035_),
    .X(_049_)
  );
  sky130_fd_sc_hd__nor2_1 _104_ (
    .A(req_off_sync),
    .B(req_sleep_sync),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nor2_1 _105_ (
    .A(_038_),
    .B(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__a21oi_1 _106_ (
    .A1(_002_),
    .A2(_049_),
    .B1(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__and4_1 _107_ (
    .A(_019_),
    .B(_026_),
    .C(_033_),
    .D(_044_),
    .X(_053_)
  );
  sky130_fd_sc_hd__a211o_1 _108_ (
    .A1(_002_),
    .A2(_049_),
    .B1(_051_),
    .C1(_053_),
    .X(_054_)
  );
  sky130_fd_sc_hd__a211o_1 _109_ (
    .A1(_039_),
    .A2(_048_),
    .B1(_054_),
    .C1(_043_),
    .X(next_state[2])
  );
  sky130_fd_sc_hd__a41oi_1 _110_ (
    .A1(pwr_stable),
    .A2(clk_stable),
    .A3(_029_),
    .A4(_032_),
    .B1(_039_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__a211oi_1 _111_ (
    .A1(_026_),
    .A2(_040_),
    .B1(_055_),
    .C1(retention_ready),
    .Y(error)
  );
  sky130_fd_sc_hd__a2111oi_0 _112_ (
    .A1(_039_),
    .A2(_048_),
    .B1(_054_),
    .C1(_043_),
    .D1(_017_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__xnor2_1 _113_ (
    .A(curr_state[0]),
    .B(next_state[0]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand2_1 _114_ (
    .A(_052_),
    .B(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__xor2_1 _115_ (
    .A(seq_timer[0]),
    .B(_024_),
    .X(_059_)
  );
  sky130_fd_sc_hd__nor3_1 _116_ (
    .A(_056_),
    .B(_058_),
    .C(_059_),
    .Y(_008_[0])
  );
  sky130_fd_sc_hd__nor2_1 _117_ (
    .A(_024_),
    .B(_028_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__a21oi_1 _118_ (
    .A1(seq_timer[0]),
    .A2(seq_busy),
    .B1(seq_timer[1]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nor4_1 _119_ (
    .A(_056_),
    .B(_058_),
    .C(_060_),
    .D(_061_),
    .Y(_008_[1])
  );
  sky130_fd_sc_hd__xnor2_1 _120_ (
    .A(seq_timer[2]),
    .B(_060_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nor3_1 _121_ (
    .A(_056_),
    .B(_058_),
    .C(_062_),
    .Y(_008_[2])
  );
  sky130_fd_sc_hd__nor2_1 _122_ (
    .A(_024_),
    .B(_040_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__a21oi_1 _123_ (
    .A1(seq_timer[2]),
    .A2(_060_),
    .B1(seq_timer[3]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nor4_1 _124_ (
    .A(_056_),
    .B(_058_),
    .C(_063_),
    .D(_009_),
    .Y(_008_[3])
  );
  sky130_fd_sc_hd__nor3_1 _125_ (
    .A(_018_),
    .B(_024_),
    .C(_040_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__a31oi_1 _126_ (
    .A1(seq_timer[3]),
    .A2(seq_timer[2]),
    .A3(_060_),
    .B1(seq_timer[4]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nor4_1 _127_ (
    .A(_056_),
    .B(_058_),
    .C(_010_),
    .D(_011_),
    .Y(_008_[4])
  );
  sky130_fd_sc_hd__xnor2_1 _128_ (
    .A(seq_timer[5]),
    .B(_010_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nor3_1 _129_ (
    .A(_056_),
    .B(_058_),
    .C(_012_),
    .Y(_008_[5])
  );
  sky130_fd_sc_hd__a21oi_1 _130_ (
    .A1(seq_timer[5]),
    .A2(_010_),
    .B1(seq_timer[6]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand3_1 _131_ (
    .A(seq_timer[6]),
    .B(seq_timer[5]),
    .C(_010_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nor4b_1 _132_ (
    .A(_056_),
    .B(_058_),
    .C(_013_),
    .D_N(_014_),
    .Y(_008_[6])
  );
  sky130_fd_sc_hd__xor2_1 _133_ (
    .A(seq_timer[7]),
    .B(_014_),
    .X(_015_)
  );
  sky130_fd_sc_hd__nor3_1 _134_ (
    .A(_056_),
    .B(_058_),
    .C(_015_),
    .Y(_008_[7])
  );
  sky130_fd_sc_hd__nand2_1 _135_ (
    .A(_030_),
    .B(_032_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__o22ai_1 _136_ (
    .A1(curr_state[2]),
    .A2(_022_),
    .B1(_027_),
    .B2(_016_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__a21boi_0 _137_ (
    .A1(curr_state[1]),
    .A2(curr_state[2]),
    .B1_N(curr_state[0]),
    .Y(_003_[0])
  );
  sky130_fd_sc_hd__or3_1 _138_ (
    .A(_002_),
    .B(_033_),
    .C(_039_),
    .X(_003_[1])
  );
  sky130_fd_sc_hd__a211o_1 _139_ (
    .A1(_017_),
    .A2(_023_),
    .B1(_006_),
    .C1(_039_),
    .X(_005_)
  );
  sky130_fd_sc_hd__nor4_1 _140_ (
    .A(curr_state[1]),
    .B(_017_),
    .C(seq_timer[1]),
    .D(_027_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__dfrtp_1 _141_ (
    .CLK(clk),
    .D(_000_),
    .Q(clk_gate_en),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _142_ (
    .CLK(clk),
    .D(_002_),
    .Q(pwr_gate_en),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _143_ (
    .CLK(clk),
    .D(_005_),
    .Q(retention_en),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _144_ (
    .CLK(clk),
    .D(_007_),
    .Q(retention_save),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _145_ (
    .CLK(clk),
    .D(_006_),
    .Q(retention_restore),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfstp_2 _146_ (
    .CLK(clk),
    .D(_001_[1]),
    .Q(dvfs_ctrl[1]),
    .SET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _147_ (
    .CLK(clk),
    .D(_004_),
    .Q(reset_ctrl),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _148_ (
    .CLK(clk),
    .D(_003_[0]),
    .Q(pwr_state[0]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _149_ (
    .CLK(clk),
    .D(_003_[1]),
    .Q(pwr_state[1]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _150_ (
    .CLK(clk),
    .D(next_state[0]),
    .Q(curr_state[0]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _151_ (
    .CLK(clk),
    .D(next_state[1]),
    .Q(curr_state[1]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _152_ (
    .CLK(clk),
    .D(next_state[2]),
    .Q(curr_state[2]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _153_ (
    .CLK(clk),
    .D(_008_[0]),
    .Q(seq_timer[0]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _154_ (
    .CLK(clk),
    .D(_008_[1]),
    .Q(seq_timer[1]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _155_ (
    .CLK(clk),
    .D(_008_[2]),
    .Q(seq_timer[2]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _156_ (
    .CLK(clk),
    .D(_008_[3]),
    .Q(seq_timer[3]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _157_ (
    .CLK(clk),
    .D(_008_[4]),
    .Q(seq_timer[4]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _158_ (
    .CLK(clk),
    .D(_008_[5]),
    .Q(seq_timer[5]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _159_ (
    .CLK(clk),
    .D(_008_[6]),
    .Q(seq_timer[6]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _160_ (
    .CLK(clk),
    .D(_008_[7]),
    .Q(seq_timer[7]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _161_ (
    .CLK(clk),
    .D(wake_up),
    .Q(sync_stage1[0]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _162_ (
    .CLK(clk),
    .D(req_off),
    .Q(sync_stage1[1]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _163_ (
    .CLK(clk),
    .D(req_sleep),
    .Q(sync_stage1[2]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _164_ (
    .CLK(clk),
    .D(req_idle),
    .Q(sync_stage1[3]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _165_ (
    .CLK(clk),
    .D(sync_stage1[0]),
    .Q(wake_up_sync),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _166_ (
    .CLK(clk),
    .D(sync_stage1[1]),
    .Q(req_off_sync),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _167_ (
    .CLK(clk),
    .D(sync_stage1[2]),
    .Q(req_sleep_sync),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _168_ (
    .CLK(clk),
    .D(sync_stage1[3]),
    .Q(req_idle_sync),
    .RESET_B(reset_n)
  );
  assign _001_[0] = 1'h1;
  assign dvfs_ctrl[0] = 1'h1;
endmodule
