/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module pmu_fsm(clk, reset_n, req_idle, req_sleep, req_off, wake_up, clk_gate_en, pwr_gate_en, retention_en, dvfs_ctrl, reset_ctrl);
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  input clk;
  output clk_gate_en;
  wire [1:0] curr_state;
  output [1:0] dvfs_ctrl;
  wire [1:0] next_state;
  output pwr_gate_en;
  input req_idle;
  input req_off;
  input req_sleep;
  output reset_ctrl;
  input reset_n;
  output retention_en;
  input wake_up;
  sky130_fd_sc_hd__clkinv_1 _10_ (
    .A(curr_state[0]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _11_ (
    .A(req_off),
    .Y(_03_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _12_ (
    .A(curr_state[1]),
    .SLEEP(curr_state[0]),
    .X(clk_gate_en)
  );
  sky130_fd_sc_hd__nand2_1 _13_ (
    .A(curr_state[1]),
    .B(_02_),
    .Y(dvfs_ctrl[1])
  );
  sky130_fd_sc_hd__and2_0 _14_ (
    .A(curr_state[1]),
    .B(curr_state[0]),
    .X(reset_ctrl)
  );
  sky130_fd_sc_hd__nand3_1 _15_ (
    .A(curr_state[1]),
    .B(_02_),
    .C(req_off),
    .Y(_04_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _16_ (
    .A(req_sleep),
    .SLEEP(req_idle),
    .X(_05_)
  );
  sky130_fd_sc_hd__o21ai_0 _17_ (
    .A1(clk_gate_en),
    .A2(_05_),
    .B1(_04_),
    .Y(_00_[0])
  );
  sky130_fd_sc_hd__or3_1 _18_ (
    .A(curr_state[1]),
    .B(curr_state[0]),
    .C(req_idle),
    .X(_06_)
  );
  sky130_fd_sc_hd__nand3b_1 _19_ (
    .A_N(curr_state[1]),
    .B(curr_state[0]),
    .C(req_sleep),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nand3_1 _20_ (
    .A(_04_),
    .B(_06_),
    .C(_07_),
    .Y(_00_[1])
  );
  sky130_fd_sc_hd__o32a_1 _21_ (
    .A1(curr_state[1]),
    .A2(_02_),
    .A3(wake_up),
    .B1(_06_),
    .B2(req_off),
    .X(_08_)
  );
  sky130_fd_sc_hd__o21ai_0 _22_ (
    .A1(curr_state[0]),
    .A2(_03_),
    .B1(curr_state[1]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__o22a_1 _23_ (
    .A1(req_sleep),
    .A2(_08_),
    .B1(_09_),
    .B2(wake_up),
    .X(_01_)
  );
  sky130_fd_sc_hd__buf_1 _24_ (
    .A(curr_state[1]),
    .X(pwr_gate_en)
  );
  sky130_fd_sc_hd__dfrtp_1 _25_ (
    .CLK(clk),
    .D(next_state[0]),
    .Q(curr_state[0]),
    .RESET_B(reset_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _26_ (
    .CLK(clk),
    .D(next_state[1]),
    .Q(curr_state[1]),
    .RESET_B(reset_n)
  );
  // Inferred Latch - commenting here at the moment, will check the RTL later
  // \$_DLATCH_P_  _27_ (
  //   .D(_00_[0]),
  //   .E(_01_),
  //   .Q(next_state[0])
  // );
  // \$_DLATCH_P_  _28_ (
  //   .D(_00_[1]),
  //   .E(_01_),
  //   .Q(next_state[1])
  // );
  assign dvfs_ctrl[0] = 1'h1;
  assign retention_en = 1'h0;
endmodule
