/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module incomp_if(i0, i1, i2, y);
  input i0;
  input i1;
  input i2;
  output y;
  \$_DLATCH_P_  _0_ (
    .D(i1),
    .E(i0),
    .Q(y)
  );
endmodule
