/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module incomp_if2(i0, i1, i2, i3, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input i0;
  input i1;
  input i2;
  input i3;
  output y;
  sky130_fd_sc_hd__mux2_1 _08_ (
    .A0(_07_),
    .A1(_05_),
    .S(_04_),
    .X(_02_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _09_ (
    .A(_04_),
    .SLEEP(_06_),
    .X(_03_)
  );
  \$_DLATCH_P_  _10_ (
    .D(_00_),
    .E(_01_),
    .Q(y)
  );
  assign _07_ = i3;
  assign _05_ = i1;
  assign _04_ = i0;
  assign _00_ = _02_;
  assign _06_ = i2;
  assign _01_ = _03_;
endmodule
