/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module incomp_case(i0, i1, i2, sel, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  input i0;
  input i1;
  input i2;
  input [1:0] sel;
  output y;
  sky130_fd_sc_hd__clkinv_1 _11_ (
    .A(_10_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _12_ (
    .A(_09_),
    .SLEEP(_10_),
    .X(_08_)
  );
  sky130_fd_sc_hd__mux2_1 _13_ (
    .A0(_06_),
    .A1(_07_),
    .S(_08_),
    .X(_04_)
  );
  \$_DLATCH_P_  _14_ (
    .D(_00_),
    .E(_01_),
    .Q(y)
  );
  assign _09_ = sel[0];
  assign _10_ = sel[1];
  assign _06_ = i0;
  assign _07_ = i1;
  assign _00_ = _04_;
  assign _01_ = _05_;
endmodule
