/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module dff_asyncres_syncres(clk, async_reset, sync_reset, d, q);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  input async_reset;
  input clk;
  input d;
  output q;
  input sync_reset;
  sky130_fd_sc_hd__clkinv_1 _7_ (
    .A(_2_),
    .Y(_3_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _8_ (
    .A(_4_),
    .SLEEP(_5_),
    .X(_1_)
  );
  sky130_fd_sc_hd__dfrtp_1 _9_ (
    .CLK(clk),
    .D(_0_),
    .Q(q),
    .RESET_B(_6_)
  );
  assign _2_ = async_reset;
  assign _6_ = _3_;
  assign _4_ = d;
  assign _5_ = sync_reset;
  assign _0_ = _1_;
endmodule
