/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module dff_asyncres(clk, async_reset, d, q);
  wire _0_;
  wire _1_;
  wire _2_;
  input async_reset;
  input clk;
  input d;
  output q;
  sky130_fd_sc_hd__clkinv_1 _3_ (
    .A(_0_),
    .Y(_1_)
  );
  sky130_fd_sc_hd__dfrtp_1 _4_ (
    .CLK(clk),
    .D(d),
    .Q(q),
    .RESET_B(_2_)
  );
  assign _0_ = async_reset;
  assign _2_ = _1_;
endmodule
