/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module counter_opt2(clk, reset, q);
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  input clk;
  wire [2:0] count;
  output q;
  input reset;
  sky130_fd_sc_hd__clkinv_1 _18_ (
    .A(_14_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__clkinv_1 _19_ (
    .A(_09_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor3b_1 _20_ (
    .A(_10_),
    .B(_09_),
    .C_N(_11_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nand2_1 _21_ (
    .A(_10_),
    .B(_09_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__xor2_1 _22_ (
    .A(_10_),
    .B(_09_),
    .X(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _23_ (
    .A(_11_),
    .B(_12_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__clkinv_1 _24_ (
    .A(_14_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__clkinv_1 _25_ (
    .A(_14_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__dfrtp_1 _26_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(count[0]),
    .RESET_B(_15_)
  );
  sky130_fd_sc_hd__dfrtp_1 _27_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(count[1]),
    .RESET_B(_16_)
  );
  sky130_fd_sc_hd__dfrtp_1 _28_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(count[2]),
    .RESET_B(_17_)
  );
  assign _14_ = reset;
  assign _17_ = _08_;
  assign _11_ = count[2];
  assign q = _13_;
  assign _10_ = count[1];
  assign _09_ = count[0];
  assign _00_[1] = _04_;
  assign _00_[2] = _05_;
  assign _00_[0] = _03_;
  assign _15_ = _06_;
  assign _16_ = _07_;
endmodule
