/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module counter_opt(clk, en, reset, q);
  wire [3:0] _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  input clk;
  wire [3:0] count;
  input en;
  output q;
  input reset;
  sky130_fd_sc_hd__clkinv_1 _7_ (
    .A(_5_),
    .Y(_2_)
  );
  sky130_fd_sc_hd__xor2_1 _8_ (
    .A(_4_),
    .B(_3_),
    .X(_1_)
  );
  sky130_fd_sc_hd__dfrtp_1 _9_ (
    .CLK(clk),
    .D(_0_[0]),
    .Q(count[0]),
    .RESET_B(_6_)
  );
  assign q = count[0];
  assign _5_ = reset;
  assign _6_ = _2_;
  assign _4_ = en;
  assign _3_ = count[0];
  assign _0_[0] = _1_;
endmodule
