/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module multiple_module_opt2(a, b, c, d, y);
  input a;
  input b;
  input c;
  input d;
  wire n1;
  wire n2;
  wire n3;
  output y;
  sub_module U1 (
    .a(a),
    .b(1'h0),
    .y(n1)
  );
  sub_module U2 (
    .a(b),
    .b(c),
    .y(n2)
  );
  sub_module U3 (
    .a(n2),
    .b(d),
    .y(n3)
  );
  sub_module U4 (
    .a(n3),
    .b(n1),
    .y(y)
  );
endmodule

module sub_module(a, b, y);
  wire _0_;
  wire _1_;
  wire _2_;
  input a;
  input b;
  output y;
  sky130_fd_sc_hd__and2_0 _3_ (
    .A(_1_),
    .B(_0_),
    .X(_2_)
  );
  assign _1_ = b;
  assign _0_ = a;
  assign y = _2_;
endmodule
