/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module opt_check(a, b, c, y1, y2);
  input a;
  input b;
  input c;
  output y1;
  output y2;
  sky130_fd_sc_hd__clkinv_1 _5_ (
    .A(c),
    .Y(y2)
  );
  sky130_fd_sc_hd__and2_0 _6_ (
    .A(b),
    .B(a),
    .X(y1)
  );
endmodule
